### ISSUE TITLE
Needs Windows ico file

### ISSUE THREAD

**Issue by enxoco** [enxoco/guardrails-desktop#2]
This project needs a Windows icon file as right now it is using the generic electron icon.  Icon should be named icon.ico and placed in the build directory.

**Comment by soulspark666** [comment]
Can I do it?

**Comment by enxoco** [comment]
Go for it.

**Comment by soulspark666** [comment]
You need an icon.ico file of the icon.icns file?

**Comment by enxoco** [comment]
Yeah I guess you could use that.  That is for the Mac app, I just need the same thing for Windows.

**Comment by soulspark666** [comment]
Done #3
